# Generated by Django 4.0 on 2021-12-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(default='', max_length=50)),
                ('modPreparare', models.CharField(default='', max_length=50)),
                ('categorie', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(default='', max_length=50)),
                ('cantitate', models.IntegerField(default=0)),
                ('unitateDeMasura', models.CharField(default='', max_length=50)),
                ('idBautura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.drinks')),
            ],
        ),
    ]
